import type { Variant } from "./scenario";

const emailLike = (r: { int(n: number): number }) => `${100_000 + r.int(900_000)}`;

/** Order confirmations: RabbitMQ, a mailer, and a gift note with bytes no decoder accepts. Customers get a 503 on the order page. */
export const confirmations: Variant = {
  key: "",
  title: "The Poison Pill",
  summary: "Customers cannot see their order status and confirmation emails are not going out. Find out why.",
  symptom: { kind: "http_503", surface: "order status" },
  page: { severity: "SEV2", title: "Order status page returning 503", body: "Customers of {brand} cannot see their order status and confirmations are not going out. You are the primary on-call." },
  labels: { edge: "edge-gateway", api: "orders-api", queue: "order-confirmations", consumer: "mailer-worker", partner: "email-provider" },
  queueCard: "RabbitMQ",
  consumerVersion: "v56",
  consumerPrevVersion: "v55",
  ref: (n) => `msg-${n.toString(16)}`,
  field: { name: "gift_note", problem: "is not valid UTF-8" },
  edgeLine: (r) => `GET /orders/${emailLike(r)}/status 503, upstream "orders-api:8080" said confirmation not ready, client 10.0.${r.int(256)}.${r.int(256)}`,
  apiLine: (r) => `order ${emailLike(r)}: confirmation still pending after 3000 ms, answering 503`,
  consumerOk: (r) => `confirmation for order ${emailLike(r)} sent, provider 202 in ${150 + r.int(60)} ms`,
  partnerOk: (r) => `POST /v3/send 202 ${140 + r.int(70)}ms`,
  partnerStatus: "email-provider status page",
  depth: { label: "Messages ready", unit: "msgs", word: "messages ready" },
  brokerReveal: (n) => `broker: ${n} messages ready, none acknowledged for minutes; the same delivery keeps coming back to a consumer that then disconnects`,
  depthReveal: (n) => `order-confirmations: ${n} ready, publish rate normal, consume rate near zero. Publishers are fine; nothing is draining it`,
  crashReveal: (s) => `mailer-worker: every crash is on message ${confirmations.ref(s.msgId)}: field gift_note is not valid UTF-8; delivered ${800 + (s.msgId % 700)} times, never acknowledged`,
  crashLine: (r) => `unhandled exception in handler, message returned to the queue (delivery ${300 + r.int(4000)})`,
  stuckLine: (n) => `order-confirmations: ${n} messages ready, 0 acknowledged in the last 60 s, consumers reconnecting`,
  okLine: (n) => `order-confirmations: ${n} messages ready, consumers connected`,
  peekCommand: "rabbitmqadmin get queue=order-confirmations ackmode=ack_requeue_true count=1",
  moveCommand: "rabbitmqadmin dead-letter --queue order-confirmations --message-id <id from the crash log>",
  purgeCommand: "rabbitmqctl purge_queue order-confirmations",
  filler: {
    sev3: "SEV3 resolved: search-api p99 above 800 ms. Duration 14 min. Postmortem PM-261.",
    pm: "PM-261 is up for review. A cache TTL change, reverted within the hour.",
    pmNote: "left two comments on the timeline",
    disk: { text: "rotated the nginx logs on the edge nodes", code: "/var/log   61% used   (was 92%)" },
    cert: "renewed the TLS certificate for *.{domain}. Next expiry in 60 days.",
    prevSha: "c41f8a7",
    prevChange: "Retry backoff tuning",
    apiSha: "b70c2de",
    apiChange: "Add order note to the API response",
    workerSha: "e5b2a19",
    workerChange: "Bump SMTP client to 3.1 (#2204)",
  },
  deployReveal: `mailer-worker v56 by {deployer}, 3 h ago: "bump SMTP client to 3.1"; it sent confirmations without trouble for hours afterwards. v55 ran 12 days`,
  asks: {
    deployer: "v56 is just the SMTP client bump. It ran fine for hours after I shipped it, so I'd look somewhere else.",
    infra: "the queue is backed up because the email provider is slow, I'm fairly sure. Restart the workers and it should clear. Broker CPU is fine.",
    support: "customers just see a 503 on their order page. The first ticket came about 45 minutes ago from someone whose order had a gift note pasted in from another app, and everything after it is waiting too.",
    secondary: "the workers restart every 30 s and the queue is not draining at all. That looks like something blocking the front, not a slow provider.",
  },
  hotspots: {
    "laptop.slack.infra": { kind: "clue", label: "Laptop: Slack #infra", author: "infra", text: "the mailer-worker pods have been restarting on and off for the last hour, no idea why yet" },
    "laptop.slack.deploys": { kind: "herring", label: "Laptop: Slack #deploys", author: "deployer", text: "mailer-worker v56 is out, just the SMTP client bump. Heading to lunch" },
    "phone.mention": { kind: "clue", label: "Phone: new mention", text: "@{brand} ordered 40 min ago, no confirmation email and the order page says 503??", appearsAt: "incident_start" },
    "table.neighbours": { kind: "clue", label: "The next table", text: "I keep refreshing my order and it just says service unavailable." },
    "wall.poster": { kind: "herring", label: "Poster on the wall", text: "{brand}: FREE SHIPPING THIS WEEKEND" },
  },
  lessons: {
    dnf: "One message with a malformed gift_note sat at the head of order-confirmations and crashed every consumer that picked it up. The queue was not slow, it was blocked. The crash logs name the message; setting it aside unblocks everything behind it.",
    purge: "Purging the queue threw away every valid confirmation, and the publisher sent the bad message again. Set the one bad message aside instead of dropping the whole queue.",
    restart: "Restarting the consumers bought time: they drained the queue until they reached the bad message again. When the same crash repeats, look for what it is choking on.",
    default: "A backlog that will not drain is not always a capacity problem. One message the consumers cannot parse can block a whole queue. The crash logs name it, and a dead-letter queue is where it belongs.",
  },
  hints: [
    "Is the queue slow, or is it not moving at all?",
    "When a consumer crashes on the same delivery again and again, what does that say about the message it is holding?",
    "If restarting made it better for a while, why did it come back?",
  ],
};

/** Inventory reservations: Kafka, one partition stuck on a line with a negative quantity, and checkout falling back to a slow synchronous call. */
export const reservations: Variant = {
  key: "inventory",
  parBp: 340,
  title: "The Poison Pill: Stuck Reservations",
  summary: "Checkout fails for some customers and stock reservations are falling behind. Find out why.",
  symptom: { kind: "http_500", surface: "checkout" },
  page: { severity: "SEV2", title: "Checkout returning 500", body: "Checkout for {brand} fails for a share of customers while stock reservations pile up. You are the primary on-call." },
  labels: { edge: "edge-gateway", api: "checkout-api", queue: "inventory.reservations", consumer: "inventory-worker", partner: "warehouse-api" },
  queueCard: "Kafka · 6 partitions",
  consumerVersion: "v92",
  consumerPrevVersion: "v91",
  ref: (n) => `partition 3, offset ${1_842_000 + (n % 9000)}`,
  field: { name: "quantity", problem: "is -1, which the reservation validator rejects" },
  edgeLine: (r) => `POST /checkout 500 5001ms, upstream "checkout-api:8080" timed out reserving stock, client 10.0.${r.int(256)}.${r.int(256)}`,
  apiLine: (r) => `cart ${emailLike(r)}: reservation not confirmed within 4000 ms, the synchronous fallback timed out`,
  consumerOk: (r) => `reserved ${1 + r.int(4)} units for order ${emailLike(r)}, offset committed`,
  partnerOk: (r) => `POST /v2/stock/sync 200 ${120 + r.int(80)}ms`,
  partnerStatus: "warehouse-api status page",
  depth: { label: "Consumer lag", unit: "records", word: "records behind" },
  brokerReveal: () => "broker: all 6 partitions have a leader and a full in-sync replica set; the consumer group inventory-worker keeps rebalancing. Nothing wrong with the brokers themselves",
  depthReveal: (n) => `inventory.reservations: total consumer lag ${n} records, produce rate normal, the group's commit rate is a fraction of it. Producers are fine; this total does not say where the lag sits`,
  crashReveal: () => "inventory-worker: every crash is a validation failure on one reservation record, over and over. The logging wrapper does not print the topic partition or the offset, so this log cannot say which record",
  crashLine: (r) => `record failed validation, handler threw, offset not committed (attempt ${300 + r.int(4000)})`,
  stuckLine: (n) => `inventory.reservations: group inventory-worker rebalancing, ${n} records of lag, commits are not advancing`,
  okLine: (n) => `inventory.reservations: ${n} records of lag, group inventory-worker stable`,
  peekCommand: "",
  moveCommand: "",
  purgeCommand: "",
  partition: {
    describeCommand: "kafka-consumer-groups.sh --bootstrap-server kafka-1:9092 --describe --group inventory-worker",
    describeReveal: (s) => {
      const at = 1_842_000 + (s.msgId % 9000);
      return `group inventory-worker: partitions 0, 1, 2, 4 and 5 have LAG under 40 and their offsets move. Partition 3: CURRENT-OFFSET ${at}, LOG-END-OFFSET ${at + s.backlog}, LAG ${s.backlog}, and the committed offset has not moved in 40 minutes`;
    },
    readCommand: "kafka-console-consumer.sh --bootstrap-server kafka-1:9092 --topic inventory.reservations --partition 3 --offset <the stuck offset> --max-messages 1",
    readReveal: (s) => `partition 3, offset ${1_842_000 + (s.msgId % 9000)}: {"sku": "SKU-71310", "quantity": -1, "source": "bulk-import"}. The validator rejects the negative quantity every time; the records behind it look normal`,
    skipLabel: "Skip the bad offset for the consumer group",
    skipCommand: "kafka-consumer-groups.sh --bootstrap-server kafka-1:9092 --group inventory-worker --topic inventory.reservations:3 --reset-offsets --to-offset <stuck offset + 1> --execute",
    skipReveal: (s) => `workers paused, group inventory-worker on partition 3 moved from offset ${1_842_000 + (s.msgId % 9000)} to ${1_842_001 + (s.msgId % 9000)}, workers resumed: one record skipped, the rest of the partition is being consumed`,
    resetLabel: "Reset the consumer group to the latest offsets",
    resetCommand: "kafka-consumer-groups.sh --bootstrap-server kafka-1:9092 --group inventory-worker --all-topics --reset-offsets --to-latest --execute",
    resetReveal: "group inventory-worker reset to the latest offsets on all 6 partitions: every unprocessed reservation was skipped",
  },
  filler: {
    sev3: "SEV3 resolved: image-cdn cache hit rate below 70%. Duration 22 min. Postmortem PM-262.",
    pm: "PM-262 is up for review. A purge job that ran twice, fixed by making it idempotent.",
    pmNote: "added the purge timings to the timeline",
    disk: { text: "vacuumed the audit tables on the reporting host", code: "/data   47% used   (was 79%)" },
    cert: "renewed the TLS certificate for the *.{domain} staging hosts. Next expiry in 90 days.",
    prevSha: "9d2e6b4",
    prevChange: "Consumer group rebalance tuning",
    apiSha: "7f0a3c1",
    apiChange: "Return the stock hold id in the checkout response",
    workerSha: "2c8d5e0",
    workerChange: "Batch reservation writes (#2210)",
  },
  deployReveal: `inventory-worker v92 by {deployer}, 3 h ago: "batch reservation writes, 50 per commit"; it committed batches cleanly for hours afterwards. v91 ran 9 days`,
  asks: {
    deployer: "v92 batches the reservation writes, 50 per commit. It has been fine since this afternoon, so I doubt it's the batching.",
    infra: "Kafka brokers are healthy. The lag is the warehouse API being slow, I'd bump the consumer count and let it catch up.",
    support: "customers get a 500 at the pay step, some of them and not others. The first person to write in uses our bulk-order API, and her import had an odd line item.",
    secondary: "the lag is not spread evenly. Some partitions move and one does not, so that does not look like a load problem. The consumer group will tell you which.",
  },
  hotspots: {
    "laptop.slack.infra": { kind: "clue", label: "Laptop: Slack #infra", author: "infra", text: "inventory-worker is in CrashLoopBackOff again. Been on and off for about 40 minutes" },
    "laptop.slack.deploys": { kind: "herring", label: "Laptop: Slack #deploys", author: "deployer", text: "inventory-worker v92 is out: batched reservation writes, no schema change" },
    "phone.mention": { kind: "clue", label: "Phone: new mention", text: "@{brand} checkout has thrown a 500 for half an hour, tried three times", appearsAt: "incident_start" },
    "table.neighbours": { kind: "clue", label: "The next table", text: "Mine went through and my friend's bulk order keeps failing at the pay step. Same site, same minute." },
    "wall.poster": { kind: "herring", label: "Poster on the wall", text: "{brand} FLASH SALE 50% today" },
  },
  lessons: {
    dnf: "One reservation with a quantity of -1 sat on a single partition and crashed the consumer each time it was delivered. Everything behind it waited, and checkout fell back to a slow synchronous call. The total lag hides which partition is stuck; the consumer group's own view shows it, and skipping that one offset unblocks the rest.",
    purge: "Resetting the whole group to the latest offsets skipped every waiting reservation, and the bulk import sent the bad line again. Skip the single bad offset on the one partition instead of skipping everything.",
    restart: "Restarting the consumers only worked until they reached the bad offset again. When the lag stays on one partition, look at the record at its committed offset.",
    default: "Lag on one partition is a different problem from lag on all of them, and a total hides the difference. Describing the consumer group shows the stuck partition and its offset; reading that record shows why, and skipping just that offset sets it aside.",
  },
  hints: [
    "Is the lag on every partition, or on one? Which view of the consumer group would show it?",
    "What does the group's committed offset on the lagging partition say, and what sits at that offset?",
    "If skipping ahead is the fix, what do you lose by skipping too far?",
  ],
};

export const VARIANTS: readonly Variant[] = [confirmations, reservations];
