import type { Variant } from "./scenario";

const id6 = (r: { int(n: number): number }) => `${100_000 + r.int(900_000)}`;

/** An analytics report on the primary; the cart reads from the replica, so checkout hits a version conflict. */
export const analytics: Variant = {
  key: "",
  title: "Replica Lag Shows Old Carts",
  summary: "Carts show old items and checkout fails for some customers. Find out why the site does not see the latest data.",
  symptom: { kind: "http_500", surface: "checkout" },
  page: { severity: "SEV2", title: "Checkout returning 500 and carts out of date", body: "Customers of {brand} see items vanish from their cart and checkout fails at the pay step. You are the primary on-call." },
  labels: { edge: "edge-gateway", api: "cart-api", cache: "cart-cache", primary: "postgres-primary", replica: "postgres-replica-1", batch: "reporting" },
  apiVersion: "v207",
  edgeLine: (r) => `POST /checkout 500 ${180 + r.int(120)}ms, upstream "cart-api:8080" returned an unhandled version conflict, client 10.0.${r.int(256)}.${r.int(256)}`,
  apiLine: (r) => `cart ${id6(r)}: version conflict, read v${10 + r.int(30)} from the read replica but the cart is at v${41 + r.int(30)}, aborting checkout`,
  apiOk: (r) => `GET /cart/${id6(r)} 200 ${22 + r.int(30)}ms`,
  batchLine: (r) => `quarterly_revenue_by_sku: scanned ${40 + r.int(50)}M of 610M order lines, still running`,
  batchDetail: "1 long query",
  lagReveal: (l) => `postgres-replica-1 is ${l} s behind and the gap is widening; WAL volume on postgres-primary is about ten times normal`,
  replicaLogReveal: (l) => `postgres-replica-1: replay ${l} s behind and growing; the replica is healthy and applying WAL as fast as it can, the primary is sending far more than usual`,
  replicaLine: (l, r) => `replay is ${l + r.int(3)} s behind the primary; still applying WAL received ${l + r.int(3)} s ago`,
  failoverTail: "the long job restarts on the new primary",
  filler: {
    sev3: "SEV3 resolved: search-api p99 above 800 ms. Duration 14 min. Postmortem PM-263.",
    pm: "PM-263 is up for review. A missing index on a filter column, added within the hour.",
    pmNote: "left a comment on the query plan",
    disk: { text: "compacted the metrics store on the monitoring nodes", code: "/var/lib/prometheus   44% used   (was 81%)" },
    cert: "renewed the TLS certificate for *.{domain}. Next expiry in 60 days.",
    prevSha: "4be07d3",
    prevChange: "Trim response payloads",
    apiSha: "a18f6c5",
    apiChange: "Show tax in the cart total (#3391)",
  },
  findLabel: "List long-running statements",
  findCommand: "SELECT pid, usename, now() - xact_start AS running, left(query, 60) FROM pg_stat_activity WHERE state <> 'idle' ORDER BY xact_start;",
  findReveal: (pid) => `pg_stat_activity: pid ${pid}, user bi_reporting, running 58 min: a quarterly revenue query over the whole order_lines table (a full scan and a huge sort). Nothing else on the primary has run longer than a few seconds`,
  stopLabel: "Terminate the report query",
  stopCommand: "SELECT pg_terminate_backend(<pid of the long query>);",
  stopReveal: (pid) => `pid ${pid} terminated; the primary's write volume is back to normal and the replica is catching up`,
  deployReveal: `cart-api v207 by {deployer}, 4 h ago: "show tax in the cart total"; it ran without errors for hours afterwards. v206 ran 8 days`,
  asks: {
    deployer: "v207 only adds the tax line to the cart total. It does read carts from the replica, it has for years and that was never a problem.",
    infra: "it's the cache, I'm pretty sure: stale cart entries. Flush redis and it should sort itself out. Replica lag alert has been flapping, it always does when the nightly stuff runs.",
    support: "customers say an item they added disappears from the cart and then comes back, and the pay button gives an error page. The first messages came in about an hour ago, right when the finance team's quarterly numbers were due.",
    secondary: "the replica is healthy, it is just seconds behind and getting worse. Whatever is making the primary write that much is what I would look for.",
  },
  hotspots: {
    "laptop.slack.infra": { kind: "clue", label: "Laptop: Slack #infra", author: "infra", text: "the postgres-replica-1 lag alert keeps flapping for the last hour, ignoring it until it stays red" },
    "laptop.slack.deploys": { kind: "herring", label: "Laptop: Slack #deploys", author: "deployer", text: "cart-api v207 is out: tax line in the cart total, no data model change" },
    "phone.mention": { kind: "clue", label: "Phone: new mention", text: "@{brand} I added a jacket to my cart twice and it keeps disappearing, then checkout throws an error??", appearsAt: "incident_start" },
    "table.neighbours": { kind: "clue", label: "The next table", text: "My cart shows the old stuff, then the new stuff, then the old stuff again. Then I pay and it fails." },
    "wall.poster": { kind: "herring", label: "Poster on the wall", text: "{brand}: SUMMER SALE ENDS SUNDAY" },
  },
  lessons: {
    dnf: "A quarterly report query had run for an hour on the primary and flooded the replica's replay. Carts read from the replica, so customers saw old data and checkout hit version conflicts. Listing the long-running statements on the primary finds it; ending it lets the replica catch up.",
    flush: "Flushing the cache hid the stale carts for a few minutes, but the replica was still far behind, so the next reads were stale again. When data is old at the source, clearing copies of it does not help.",
    failover: "Failing over to the lagging replica promoted a server that had missed recent writes, so committed orders were lost, and the report simply started again on the new primary. A lagging replica is not a safe place to fail over to.",
    route: "Routing reads to the primary hid the stale data, but the primary was already carrying the long query and slowed down under the extra reads. It buys time, not a fix; the load on the primary was the cause.",
    default: "Stale reads after a write usually mean a replica is behind. The question is what makes the primary write so much: a long-running statement shows up in the primary's activity list, and ending it lets the replica catch up.",
  },
  hints: [
    "Are the writes wrong, or are the reads looking at an older copy?",
    "If a replica is far behind, what could be making the primary produce more changes than it can ship?",
    "If clearing or routing around it helps for a few minutes, what is still running underneath?",
  ],
};

/** A backfill migration on the primary; the account order-history page reads from the replica and cannot find fresh orders. */
export const migration: Variant = {
  key: "migration",
  title: "Replica Lag: The Backfill",
  summary: "Customers cannot see their new orders and the order history page fails, though the orders exist. Find out why.",
  symptom: { kind: "http_502", surface: "order history" },
  page: { severity: "SEV2", title: "Order history returning 502", body: "Customers of {brand} who just placed an order get an error on their order history page. You are the primary on-call." },
  labels: { edge: "edge-gateway", api: "accounts-api", cache: "session-cache", primary: "orders-primary", replica: "orders-replica-2", batch: "migrator" },
  apiVersion: "v88",
  edgeLine: (r) => `GET /account/orders 502 ${90 + r.int(80)}ms, upstream "accounts-api:8080" closed the connection, client 10.0.${r.int(256)}.${r.int(256)}`,
  apiLine: (r) => `order ${id6(r)}: placed ${2 + r.int(6)} s ago on the primary but not found on the read replica, the history page could not render`,
  apiOk: (r) => `GET /account/profile 200 ${20 + r.int(30)}ms`,
  batchLine: (r) => `orders_v2_backfill: batch ${1200 + r.int(300)} of 4800 committed inside one open transaction`,
  batchDetail: "1 backfill running",
  lagReveal: (l) => `orders-replica-2 is ${l} s behind and the gap is widening. WAL is arriving on the replica, but its replay position has not moved for a long time. WAL volume on orders-primary is only a little above normal`,
  replicaLogReveal: (l) => `orders-replica-2: ${l} s behind and growing; received WAL keeps arriving but replay is frozen at the same position. The replica itself is healthy, with CPU and disk idle`,
  replicaLine: (l, r) => `replay is ${l + r.int(3)} s behind the primary; last replayed position unchanged, ${l + r.int(3)} s of received WAL waiting to be applied`,
  findLabel: "List sessions on the replica",
  findCommand: "SELECT pid, usename, application_name, state, now() - xact_start AS open FROM pg_stat_activity WHERE backend_type = 'client backend' ORDER BY xact_start;  -- on the replica",
  findReveal: (pid) => `pg_stat_activity on orders-replica-2: pid ${pid}, user bi_readonly, application metabase, state idle in transaction for 52 min. pg_locks: it holds an AccessShareLock on the orders table, which replaying the backfill's table rewrite needs exclusively, so replay has been waiting on it. Nothing else is open on the replica`,
  stopLabel: "Terminate the idle-in-transaction session",
  stopCommand: "SELECT pg_terminate_backend(<pid of the idle session>);  -- on the replica",
  stopReveal: (pid) => `pid ${pid} terminated; replay resumed and the replica is working through the backlog of WAL`,
  failoverTail: "the analytics tool reconnects to the new replica and leaves an idle transaction open again within the hour",
  backfill: {
    listReveal: (pid) => `pg_stat_activity on orders-primary: pid ${pid + 3011}, application migrator, open 47 min: the orders_v2 backfill is rewriting 190M rows in one transaction, at about four times the normal WAL rate. That is busy, but a replica can replay it, and it does not explain a replay that has stopped`,
    pauseLabel: "Pause the orders_v2 backfill",
    pauseCommand: "CALL backfill.pause('orders_v2');",
    pauseReveal: "backfill paused: primary CPU and WAL volume are back to normal, but orders-replica-2 is still frozen at the same replay position",
    alert: { title: "OldTransactionOpen", description: "orders-primary has a transaction open for more than 30 minutes" },
  },
  filler: {
    sev3: "SEV3 resolved: notifications-api queue depth above 2000. Duration 9 min. Postmortem PM-264.",
    pm: "PM-264 is up for review. A webhook consumer that fell behind after a retry setting change.",
    pmNote: "asked for the consumer graphs in the timeline",
    disk: { text: "pruned the old build artifacts on the CI runners", code: "/srv/builds   52% used   (was 88%)" },
    cert: "renewed the TLS certificate for the *.{domain} mail relay. Next expiry in 75 days.",
    prevSha: "d63a90e",
    prevChange: "Cache the account profile lookup",
    apiSha: "f27b4d8",
    apiChange: "Paginate order history (#1187)",
  },
  deployReveal: `accounts-api v88 by {deployer}, 5 h ago: "paginate order history"; it served the page fine for hours afterwards. v87 ran 11 days`,
  asks: {
    deployer: "v88 only paginates the history list. That page reads from the replica like it always has, the change did not touch that.",
    infra: "the replica must be broken, honestly. Fail over to it and we get a fresh server. The lag graph is ugly, but I would leave the migration alone mid-window.",
    support: "customers who just ordered say their order is not on the history page, and the page sometimes gives an error. It started about 50 minutes ago, around when the maintenance window began. The analytics team also say their dashboard on the replica has been hanging since this morning.",
    secondary: "the replica has not fallen behind so much as stopped applying anything. The migration is busy, but not busy enough to explain that. What is the replica itself waiting for?",
  },
  hotspots: {
    "laptop.slack.infra": { kind: "clue", label: "Laptop: Slack #infra", author: "infra", text: "orders-replica-2 looks stuck rather than slow since the maintenance window opened, I'll look after lunch" },
    "laptop.slack.deploys": { kind: "herring", label: "Laptop: Slack #deploys", author: "deployer", text: "accounts-api v88 is out: paginated order history, no schema change" },
    "phone.mention": { kind: "clue", label: "Phone: new mention", text: "@{brand} I ordered ten minutes ago and my order history is empty and then it just errors", appearsAt: "incident_start" },
    "table.neighbours": { kind: "clue", label: "The next table", text: "I placed an order and the history page says I have none. Then I refresh and it is there. Then it errors." },
    "wall.poster": { kind: "herring", label: "Poster on the wall", text: "{brand}: NEW AUTUMN RANGE IN STORE" },
  },
  lessons: {
    dnf: "An analytics session left idle in a transaction on the replica held a lock that the replay of the backfill's table rewrite needed, so replay stopped and the replica fell further behind. The history page reads from the replica, so new orders were missing. The backfill on the primary was busy but innocent; the replica's own session list shows the blocker, and ending that session lets replay resume.",
    flush: "Flushing the cache hid the stale pages for a while, but the replica was still frozen, so the next reads were stale again. Clearing copies does not fix an old source.",
    failover: "Failing over to a replica that had stopped replaying promoted a server that had missed recent writes, so committed orders were lost, and the same kind of blocker returned once the analytics tool reconnected. Do not fail over to a replica that is far behind.",
    route: "Routing reads to the primary hid the missing orders, but the primary was already carrying the backfill and slowed down under the extra reads. It buys time, not a fix.",
    pause: "Pausing the backfill quietened the primary, but the replica was not lagging because of the write rate. Its replay was blocked by a session on the replica itself, so the lag did not move. A busy primary is not always the cause of a lagging replica.",
    default: "A replica can fall behind because the primary writes too much, or because its own replay is blocked. When the replay position stops moving, look at the replica's sessions: a query left idle in a transaction can hold a lock that replay has to wait for.",
  },
  hints: [
    "Are the new orders missing, or is the page looking at an older copy of the data?",
    "Is the replica behind because it cannot keep up, or because it is not applying anything at all?",
    "If pausing the busy primary changes nothing, what is the replica itself waiting for?",
  ],
};

export const VARIANTS: readonly Variant[] = [analytics, migration];
