import type { DesktopContent } from "./desktop";

// Background messages make the workspace look lived-in. None of them adds a clue: the clues stay
// in the two hotspot messages (#deploys, #infra), the phone mention and the secondary's DM.
export const slowLeakDesktop: DesktopContent = {
  server: "nginx",
  channels: ["incidents", "deploys", "infra"],
  channelInfo: {
    incidents: { topic: "Active incidents only. Declare, then keep updates in a thread.", members: 38, pinned: 3 },
    deploys: { topic: "Production deploy notifications from Deploy Bot", members: 52, pinned: 1 },
    infra: { topic: "Databases, networking and platform maintenance notices", members: 24, pinned: 5 },
  },
  chat: [
    { id: "incidents.sev3", channel: "incidents", trigger: { kind: "prepage" }, minutesAgo: 1450, author: "bot", text: "SEV3 resolved: search-api p99 above 800 ms. Duration 14 min. Postmortem PM-212." },
    {
      id: "incidents.pm212",
      channel: "incidents",
      trigger: { kind: "prepage" },
      minutesAgo: 1380,
      author: "secondary",
      text: "PM-212 is up for review. Short one: a cache TTL change, reverted within the hour.",
      reactions: [{ emoji: "👀", by: ["infra", "support"] }],
      thread: [
        { author: "infra", text: "left two comments on the timeline", minutesAgo: 1310 },
        { author: "secondary", text: "thanks, fixed both", minutesAgo: 1290 },
      ],
    },
    {
      id: "deploys.v141",
      channel: "deploys",
      trigger: { kind: "prepage" },
      minutesAgo: 8640,
      author: "deploybot",
      text: "checkout-api v141 deployed to production",
      card: { service: "checkout-api", version: "v141", sha: "9f2c1ab", by: "deployer", env: "production", changes: "Bump payments SDK to 4.2", status: "succeeded" },
    },
    {
      id: "deploys.search",
      channel: "deploys",
      trigger: { kind: "prepage" },
      minutesAgo: 2890,
      author: "deploybot",
      text: "search-api v88 deployed to production",
      card: { service: "search-api", version: "v88", sha: "41be9d0", by: "secondary", env: "production", changes: "Tune the result cache TTL", status: "succeeded" },
    },
    { id: "deploys.dimas", channel: "deploys", trigger: { kind: "prepage" }, minutesAgo: 53, hotspotId: "laptop.slack.deploys", reactions: [{ emoji: "🚀", by: ["secondary"] }] },
    {
      id: "deploys.v142",
      channel: "deploys",
      trigger: { kind: "prepage" },
      minutesAgo: 52,
      author: "deploybot",
      text: "checkout-api v142 deployed to production",
      card: { service: "checkout-api", version: "v142", sha: "c41e07d", by: "deployer", env: "production", changes: "Checkout refactor (#1841)", status: "succeeded" },
    },
    { id: "infra.cert", channel: "infra", trigger: { kind: "prepage" }, minutesAgo: 190, author: "infra", text: "renewed the TLS certificate for *.{domain}. Next expiry in 60 days." },
    { id: "infra.maintenance", channel: "infra", trigger: { kind: "prepage" }, minutesAgo: 120, hotspotId: "laptop.slack.infra" },
    { id: "infra.disk", channel: "infra", trigger: { kind: "prepage" }, minutesAgo: 80, author: "infra", text: "cleaned up old logs on the logging nodes", code: "/var/log   41% used   (was 87%)" },
    { id: "infra.noisy", channel: "infra", trigger: { kind: "prepage" }, minutesAgo: 35, author: "infra", text: "postgres dashboards look noisy today, probably the nightly batch jobs" },
    { id: "dm.support.refund", channel: "dm:support", trigger: { kind: "prepage" }, minutesAgo: 25, author: "support", text: "hey, are you on call today? a customer asked about a refund, not urgent" },
    { id: "incidents.opened", channel: "incidents", trigger: { kind: "page" }, author: "bot", text: "SEV2 opened: Checkout returning 5xx. Primary: you. Secondary: {secondary}." },
    { id: "incidents.support", channel: "incidents", trigger: { kind: "alert", alertId: "checkout_latency" }, author: "support", text: "Customers are writing in: the payment step shows a gateway error." },
    {
      id: "dm.secondary.mitigated",
      channel: "dm:secondary",
      trigger: { kind: "status", status: "mitigated", afterTicks: 200 },
      author: "secondary",
      text: "5xx are gone, but checkout's pool is climbing again. Is the cause actually fixed, or did something just reset it?",
    },
    { id: "dm.deployer.changes", channel: "dm:deployer", trigger: { kind: "action", actionId: "ask.deployer.changes" }, author: "deployer", text: "v142, the checkout refactor. I moved transaction handling into a middleware, tests were green. Why, is it acting up?" },
    { id: "dm.infra.db", channel: "dm:infra", trigger: { kind: "action", actionId: "ask.infra.db" }, author: "infra", text: "postgres looks noisy today, probably the nightly batch jobs. CPU is fine though, so I wouldn't panic." },
    { id: "dm.support.impact", channel: "dm:support", trigger: { kind: "action", actionId: "ask.support.impact" }, author: "support", text: "about 1 in 25 payments fail right now. Customers get a 502 page at the payment step, and some retry and get charged nothing." },
    { id: "dm.secondary.deploy", channel: "dm:secondary", trigger: { kind: "action", actionId: "global.ask_secondary" }, author: "secondary", text: "{deployer} shipped v142 about an hour ago. Could that be it?" },
  ],
  requests: [
    { method: "GET", path: "/", type: "document", initiator: "Other", weight: 3, okStatus: 200, failsWithSymptom: false, okMs: [40, 110], failMs: [40, 110] },
    { method: "GET", path: "/assets/app.js", type: "script", initiator: "(index)", weight: 2, okStatus: 304, failsWithSymptom: false, okMs: [8, 20], failMs: [8, 20] },
    { method: "GET", path: "/assets/app.css", type: "stylesheet", initiator: "(index)", weight: 1, okStatus: 304, failsWithSymptom: false, okMs: [6, 16], failMs: [6, 16] },
    { method: "GET", path: "/img/p/{id}.webp", type: "img", initiator: "(index)", weight: 3, okStatus: 200, failsWithSymptom: false, okMs: [20, 80], failMs: [20, 80] },
    { method: "GET", path: "/products/{id}", type: "fetch", initiator: "app.js", weight: 4, okStatus: 200, failsWithSymptom: false, okMs: [25, 90], failMs: [25, 90] },
    { method: "POST", path: "/cart", type: "fetch", initiator: "app.js", weight: 2, okStatus: 201, failsWithSymptom: false, okMs: [60, 140], failMs: [60, 140] },
    { method: "POST", path: "/checkout", type: "fetch", initiator: "app.js", weight: 3, okStatus: 200, failsWithSymptom: true, okMs: [180, 420], failMs: [5000, 5200] },
  ],
};
